# Generated by Django 4.2.7 on 2025-11-13 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MobileApp', '0002_mobileproject_api_endpoint_mobilecontrol_loginlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='MobileApp.mobileproject')),
            ],
            options={
                'ordering': ['module_name'],
                'unique_together': {('project', 'module_name')},
            },
        ),
    ]
