# Generated by Django 4.2.7 on 2025-11-13 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleAndPackage', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='module',
            name='module_code',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
