# Generated by Django 5.2.8 on 2025-12-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleAndPackage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='days_limit',
            field=models.PositiveIntegerField(default=0, help_text='Number of days before auto-deactivation (0 = unlimited)'),
        ),
    ]
