# Generated by Django 5.2.8 on 2026-03-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleAndPackage', '0002_package_days_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
