# Generated by Django 4.2.7 on 2025-11-18 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0002_mobileproject_api_endpoint_mobilecontrol_loginlog_and_more'),
        ('ModuleAndPackage', '0002_alter_module_unique_together_module_module_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modules', models.ManyToManyField(to='ModuleAndPackage.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileApp.mobileproject')),
            ],
        ),
    ]
