# Generated by Django 5.0.14 on 2026-09-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleAndPackage', '0003_alter_module_module_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='users_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Optional package user count limit (0/blank = no limit)', null=True),
        ),
    ]
