# Generated by Django 5.2.8 on 2026-01-03 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MobileApp', '0001_initial'),
        ('ModuleAndPackage', '0002_package_days_limit'),
        ('StoreShop', '0004_alter_shop_client_id'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('api_endpoint', models.CharField(editable=False, max_length=250, unique=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='MobileControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=200)),
                ('license_key', models.CharField(blank=True, editable=False, max_length=19, null=True, unique=True)),
                ('login_limit', models.PositiveIntegerField(default=1)),
                ('status', models.BooleanField(default=False)),
                ('bill_status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.branch')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ModuleAndPackage.package')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StoreShop.shop')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StoreShop.store')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='MobileApp.mobileproject')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='MobileBillingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_days', models.IntegerField(default=0)),
                ('extended_login_limit', models.IntegerField(default=0)),
                ('old_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('new_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('old_login_limit', models.PositiveIntegerField()),
                ('new_login_limit', models.PositiveIntegerField()),
                ('bill_status', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_history', to='MobileApp.mobilecontrol')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=200)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to='MobileApp.mobilecontrol')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='ActiveDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('logged_in_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_devices', to='MobileApp.mobilecontrol')),
            ],
            options={
                'unique_together': {('control', 'device_id')},
            },
        ),
    ]
