# Generated by Django 5.2.8 on 2025-11-27 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MobileApp', '0001_initial'),
        ('ModuleAndPackage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilecontrol',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ModuleAndPackage.package'),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to='MobileApp.mobilecontrol'),
        ),
        migrations.AddField(
            model_name='activedevice',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_devices', to='MobileApp.mobilecontrol'),
        ),
        migrations.AddField(
            model_name='mobilecontrol',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='MobileApp.mobileproject'),
        ),
        migrations.AlterUniqueTogether(
            name='activedevice',
            unique_together={('control', 'device_id')},
        ),
        migrations.AlterUniqueTogether(
            name='mobilecontrol',
            unique_together={('project', 'client_id')},
        ),
    ]
