# Generated by Django 4.2.7 on 2025-11-06 04:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileproject',
            name='api_endpoint',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MobileControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=200)),
                ('login_limit', models.PositiveIntegerField(default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='MobileApp.mobileproject')),
            ],
            options={
                'ordering': ['-created_date'],
                'unique_together': {('project', 'client_id')},
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=200)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to='MobileApp.mobilecontrol')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='ActiveDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('logged_in_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_devices', to='MobileApp.mobilecontrol')),
            ],
            options={
                'unique_together': {('control', 'device_id')},
            },
        ),
    ]
