# Generated by Django 5.2.8 on 2025-11-27 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0002_initial'),
        ('StoreShop', '0002_store_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilecontrol',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StoreShop.store'),
        ),
    ]
