# Generated by Django 4.2.7 on 2025-11-21 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleAndPackage', '0003_package'),
        ('MobileApp', '0002_mobileproject_api_endpoint_mobilecontrol_loginlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilecontrol',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ModuleAndPackage.package'),
        ),
    ]
