# Generated by Django 5.2.8 on 2025-11-27 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0003_mobilecontrol_store'),
        ('StoreShop', '0002_store_store_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilecontrol',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='mobilecontrol',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mobilecontrol',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StoreShop.shop'),
        ),
        migrations.AlterField(
            model_name='mobilecontrol',
            name='client_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mobilecontrol',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mobilecontrol',
            name='login_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mobilecontrol',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileApp.mobileproject'),
        ),
        migrations.RemoveField(
            model_name='mobilecontrol',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='mobilecontrol',
            name='updated_date',
        ),
    ]
