# Generated by Django 5.2.8 on 2026-01-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0004_alter_mobilecontrol_login_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilecontrol',
            name='login_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
