# Generated by Django 5.2.8 on 2025-11-27 05:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0004_alter_mobilecontrol_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilecontrol',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
