# Generated by Django 5.2.8 on 2025-11-27 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0005_mobilecontrol_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilecontrol',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterUniqueTogether(
            name='mobilecontrol',
            unique_together={('project', 'client_id')},
        ),
        migrations.AddField(
            model_name='mobilecontrol',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilecontrol',
            name='license_key',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mobilecontrol',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mobilecontrol',
            name='client_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mobilecontrol',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mobilecontrol',
            name='login_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mobilecontrol',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='MobileApp.mobileproject'),
        ),
        migrations.RemoveField(
            model_name='mobilecontrol',
            name='created_at',
        ),
    ]
