# Generated by Django 5.2.8 on 2025-11-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0006_alter_mobilecontrol_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mobilecontrol',
            unique_together=set(),
        ),
    ]
