# Generated by Django 5.2.8 on 2026-01-30 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0007_alter_mobilecontrol_login_limit'),
        ('mobile_demo_licencing', '0005_demomobilelicense_expires_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activedevice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='activedevice',
            name='demo_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_devices', to='mobile_demo_licencing.demomobilelicense'),
        ),
        migrations.AlterField(
            model_name='activedevice',
            name='control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_devices', to='MobileApp.mobilecontrol'),
        ),
    ]
