# Generated by Django 5.2.8 on 2025-12-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0007_alter_mobilecontrol_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilecontrol',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
