# Generated by Django 5.2.8 on 2026-02-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0008_alter_activedevice_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebillinghistory',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mobilebillinghistory',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
