# Generated by Django 5.2.8 on 2025-12-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0008_mobilecontrol_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilecontrol',
            name='license_key',
            field=models.CharField(blank=True, editable=False, max_length=19, null=True, unique=True),
        ),
    ]
