# Generated by Django 5.2.8 on 2026-03-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0009_mobilebillinghistory_invoice_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilecontrol',
            name='licence_type',
            field=models.CharField(choices=[('new', 'New Licence'), ('transfer', 'Transfer Licence'), ('developer', 'Developer Licence')], default='new', max_length=20),
        ),
    ]
