# Generated by Django 5.2.8 on 2025-12-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0009_alter_mobilecontrol_license_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilecontrol',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
