# Generated by Django 5.2.8 on 2025-12-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0010_alter_mobilecontrol_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilecontrol',
            name='bill_status',
            field=models.BooleanField(default=False),
        ),
    ]
