# Generated by Django 5.2.8 on 2025-12-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0011_mobilecontrol_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activedevice',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
