# Generated by Django 5.2.8 on 2026-03-09 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0011_custompackage_custompackagemodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilecontrol',
            name='active_custom_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_controls', to='MobileApp.custompackage'),
        ),
    ]
