# Generated by Django 5.2.8 on 2025-12-08 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0012_activedevice_device_name'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilecontrol',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.branch'),
        ),
    ]
