# Generated by Django 5.2.8 on 2026-03-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0012_mobilecontrol_active_custom_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompackagemodule',
            name='module_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
