# Generated by Django 5.2.8 on 2026-03-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0013_custompackagemodule_module_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompackagemodule',
            name='module_code',
        ),
    ]
