# Generated by Django 5.2.8 on 2026-03-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0014_remove_custompackagemodule_module_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompackagemodule',
            name='module_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
