# Generated by Django 5.2.8 on 2026-03-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0015_custompackagemodule_module_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileproject',
            name='customized_package',
            field=models.BooleanField(default=False),
        ),
    ]
