# Generated by Django 5.2.8 on 2026-03-12 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0016_mobileproject_customized_package'),
        ('ModuleAndPackage', '0003_alter_module_module_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebillinghistory',
            name='custom_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MobileApp.custompackage'),
        ),
        migrations.AddField(
            model_name='mobilebillinghistory',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ModuleAndPackage.package'),
        ),
    ]
