# Generated by Django 5.2.8 on 2026-04-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0017_mobilebillinghistory_custom_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebillinghistory',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partially Paid', 'Partially Paid'), ('Not Paid', 'Not Paid'), ('Not Applicable', 'Not Applicable')], default='Not Applicable', max_length=20),
        ),
    ]
