# Generated by Django 5.2.8 on 2026-04-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0018_mobilebillinghistory_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilebillinghistory',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partially Paid', 'Partially Paid'), ('Not Paid', 'Not Paid'), ('Not Applicable', 'Not Applicable')], default='Not Paid', max_length=20),
        ),
    ]
