# Generated by Django 5.2.8 on 2026-04-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0019_alter_mobilebillinghistory_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebillinghistory',
            name='added_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
