# Generated by GitHub Copilot on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0020_mobilebillinghistory_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='activedevice',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
