# Generated by Django on 2026-05-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0021_activedevice_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebillinghistory',
            name='ref_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
