# Generated by Django on 2026-05-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0022_mobilebillinghistory_ref_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebillinghistory',
            name='ref_no_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
