# Generated by Django 5.0.14 on 2026-06-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0023_mobilebillinghistory_ref_no_saved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileproject',
            name='app_type',
            field=models.CharField(choices=[('mobile_app', 'Mobile app'), ('web_app', 'Web app'), ('ra', 'RA'), ('other', 'Other')], default='mobile_app', max_length=20),
        ),
    ]
