# Generated by Django 5.0.14 on 2026-06-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0024_mobileproject_app_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileproject',
            name='app_type',
            field=models.CharField(choices=[('mobile_app', '1. Mobile app'), ('web_app', '2. Web app'), ('ra', '3. RA'), ('other', '4. Other')], default='mobile_app', max_length=20),
        ),
    ]
