# Generated by Django 5.0.14 on 2026-06-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0025_alter_mobileproject_app_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileproject',
            name='app_type',
            field=models.CharField(choices=[('mobile_app', 'Mobile app'), ('web_app', 'Web app'), ('ra', 'RA'), ('other', 'Other')], default='mobile_app', max_length=20),
        ),
    ]
