# Generated by Django 5.0.14 on 2026-09-16 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0026_alter_mobileproject_app_type'),
        ('branch', '0002_branch_auto_cut'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileproject',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_projects', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='mobilecontrol',
            name='licence_type',
            field=models.CharField(choices=[('new', 'New Licence'), ('transfer', 'Transfer Licence'), ('developer', 'Developer Licence'), ('demo', 'Demo Licence')], default='new', max_length=20),
        ),
    ]
