# Generated by Django 5.2.8 on 2026-01-29 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MobileApp', '0007_alter_mobilecontrol_login_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoMobileLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_license', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('original_license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_licenses', to='MobileApp.mobilecontrol')),
            ],
        ),
    ]
