# Generated by Django 5.2.8 on 2026-01-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_demo_licencing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demomobilelicense',
            name='demo_login_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
