# Generated by Django 5.2.8 on 2026-01-30 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0007_alter_mobilecontrol_login_limit'),
        ('mobile_demo_licencing', '0002_demomobilelicense_demo_login_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='demomobilelicense',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demomobilelicense',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demomobilelicense',
            name='original_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demo_licenses', to='MobileApp.mobilecontrol'),
        ),
    ]
