# Generated by Django 5.2.8 on 2026-01-30 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0007_alter_mobilecontrol_login_limit'),
        ('ModuleAndPackage', '0002_package_days_limit'),
        ('mobile_demo_licencing', '0003_demomobilelicense_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demomobilelicense',
            name='project_name',
        ),
        migrations.AddField(
            model_name='demomobilelicense',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ModuleAndPackage.package'),
        ),
        migrations.AddField(
            model_name='demomobilelicense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MobileApp.mobileproject'),
        ),
    ]
