# Generated by Django 5.2.8 on 2026-01-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_demo_licencing', '0004_remove_demomobilelicense_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demomobilelicense',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
