# Generated by Django 5.2.8 on 2026-02-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_demo_licencing', '0005_demomobilelicense_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='demomobilelicense',
            name='client_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
