# Generated by Django 5.2.8 on 2025-11-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
