# Generated by Django 4.2.7 on 2025-11-10 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StoreShop', '0002_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='client_id',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
