# Generated by Django 4.2.7 on 2025-11-18 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('StoreShop', '0003_shop_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
        ),
        migrations.AddField(
            model_name='shop',
            name='place',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
