# Generated by Django 5.2.8 on 2025-12-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreShop', '0003_shop_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='client_id',
            field=models.CharField(editable=False, max_length=13, unique=True),
        ),
    ]
