# Generated by Django 5.2.8 on 2026-02-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreShop', '0005_shop_created_at_shop_created_by_store_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
