# Generated by Django 5.2.8 on 2026-03-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreShop', '0006_alter_shop_contact_no_alter_shop_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
