# Generated by Django 5.0.14 on 2026-05-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreShop', '0007_shop_created_by_name_store_created_by_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='client_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
