# Generated by Django 5.0.14 on 2026-07-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreShop', '0008_client_id_editable_longer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='currency_code',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
