# Generated by Django 5.0.14 on 2026-08-31 11:09

from django.db import migrations, models


def convert_empty_email_to_null(apps, schema_editor):
    Shop = apps.get_model('StoreShop', 'Shop')

    # Empty strings -> NULL (so they remain allowed/blank)
    Shop.objects.filter(email='').update(email=None)

    # Duplicate non-empty emails: keep the first created row, null the rest
    seen = set()
    for shop in Shop.objects.exclude(email__isnull=True).order_by('id'):
        if shop.email in seen:
            shop.email = None
            shop.save(update_fields=['email'])
        else:
            seen.add(shop.email)


class Migration(migrations.Migration):

    dependencies = [
        ('StoreShop', '0009_shop_country_shop_currency_code'),
    ]

    operations = [
        migrations.RunPython(convert_empty_email_to_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
