# Generated by Django 5.0.14 on 2026-09-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreShop', '0010_alter_shop_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
