# Generated by Django 4.2.7 on 2025-11-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_webproject_api_endpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webproject',
            name='api_endpoint',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
