# Generated by Django 4.2.7 on 2025-11-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_alter_webproject_api_endpoint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webcontrol',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='webproject',
            name='api_endpoint',
        ),
        migrations.DeleteModel(
            name='LoginLog',
        ),
    ]
