# Generated by Django 4.2.7 on 2025-11-04 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_alter_webcontrol_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webproject',
            name='api_endpoint',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='webcontrol',
            unique_together={('project', 'client_id')},
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=200)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to='WebApp.webcontrol')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
