# Generated by Django 4.2.7 on 2025-11-04 11:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_webproject_api_endpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_uuid', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('device_token', models.CharField(blank=True, max_length=128, null=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='WebApp.webcontrol')),
            ],
            options={
                'unique_together': {('control', 'device_uuid')},
            },
        ),
    ]
