# Generated by Django 4.2.7 on 2025-11-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
