# Generated by Django 4.2.7 on 2025-11-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_loginlog_device_id_delete_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginlog',
            name='device_id',
        ),
    ]
