# Generated by Django 4.2.7 on 2025-11-05 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_remove_loginlog_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('logged_in_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_devices', to='WebApp.webcontrol')),
            ],
            options={
                'unique_together': {('control', 'device_id')},
            },
        ),
    ]
