# Generated by Django 5.0.2 on 2025-10-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('RITS TANZANIA', 'RITS TANZANIA'), ('RITS OMAN', 'RITS OMAN'), ('IMC CHAVAKKAD', 'IMC CHAVAKKAD'), ('SMART', 'SMART'), ('ZENOX', 'ZENOX'), ('WINWAY', 'WINWAY'), ('SYSMAC KTTYADI', 'SYSMAC KTTYADI'), ('RITS UAE', 'RITS UAE'), ('SATHYAM', 'SATHYAM'), ('RUBIX', 'RUBIX'), ('RITS KSA', 'RITS KSA'), ('RITS QATAR', 'RITS QATAR'), ('RITS H.O', 'RITS H.O'), ('IMC MUKKAM', 'IMC MUKKAM'), ('IMC KOOTHUPARAMBA', 'IMC KOOTHUPARAMBA'), ('IMC KOLLAM', 'IMC KOLLAM'), ('IMC PALAKKAD', 'IMC PALAKKAD'), ('IMC', 'IMC'), ('FLASH INNOVATIONS', 'FLASH INNOVATIONS'), ('FINAAX', 'FINAAX'), ('ASTRIC', 'ASTRIC'), ('APEXMAX', 'APEXMAX'), ('ABSY IT SOLUTIONS', 'ABSY IT SOLUTIONS'), ('SYSMAC', 'SYSMAC')], max_length=100)),
                ('level', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('User', 'User')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
