# Generated by Django 5.2.8 on 2025-12-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='allowed_menus',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
