# Generated by Django 5.0.2 on 2025-10-10 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='role',
            new_name='branch',
        ),
        migrations.AddField(
            model_name='users',
            name='user_role',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
