# Generated by Django 5.2.8 on 2026-02-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_users_allowed_menus'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='branch',
        ),
        migrations.AddField(
            model_name='users',
            name='branches',
            field=models.ManyToManyField(blank=True, to='branch.branch'),
        ),
    ]
