# Generated by Django 5.2.8 on 2026-02-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_users_branch_users_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='level',
            field=models.CharField(choices=[('Super User', 'Super User'), ('User', 'User')], max_length=20),
        ),
    ]
