# Generated by Django 5.2.8 on 2025-11-26 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_users_profile_image'),
        ('branch', '0004_remove_branch_currency_decimal_branch_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.branch'),
        ),
    ]
