# Generated by Django 5.0.14 on 2026-06-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_add_is_active_to_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='allowed_app_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
