# Generated by Django 5.0.14 on 2026-08-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_index=True, max_length=150)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_type', models.CharField(blank=True, default='', max_length=50)),
                ('action', models.CharField(max_length=255)),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
