# Generated by Django 5.0.14 on 2026-08-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='details',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='object_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
