# Generated by Django 5.2.8 on 2025-11-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(default='', max_length=200)),
                ('country', models.CharField(choices=[('India', 'India'), ('United Arab Emirates', 'UAE'), ('Saudi Arabia', 'Saudi Arabia'), ('Qatar', 'Qatar'), ('Kuwait', 'Kuwait'), ('Oman', 'Oman'), ('Bahrain', 'Bahrain'), ('United States', 'USA'), ('United Kingdom', 'UK'), ('Canada', 'Canada'), ('Australia', 'Australia')], default='India', max_length=100)),
                ('currency_code', models.CharField(default='INR', max_length=10)),
            ],
        ),
    ]
