# Generated by Django 5.2.8 on 2025-11-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('United Arab Emirates', 'UAE'), ('Saudi Arabia', 'Saudi Arabia'), ('Qatar', 'Qatar'), ('Kuwait', 'Kuwait'), ('Oman', 'Oman'), ('Bahrain', 'Bahrain'), ('United States', 'USA'), ('United Kingdom', 'UK'), ('Canada', 'Canada'), ('Australia', 'Australia')], default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='currency_decimal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
