# Generated by Django 5.0.14 on 2026-07-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='auto_cut',
            field=models.CharField(choices=[('disable', 'Disable'), ('enable', 'Enable')], default='disable', max_length=10),
        ),
    ]
