# Generated by Django 5.2.8 on 2025-11-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_branch_country_branch_currency_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='place',
            field=models.CharField(default='', max_length=200),
        ),
    ]
