# Generated by Django 5.2.8 on 2025-11-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_branch_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='currency_decimal',
        ),
        migrations.AddField(
            model_name='branch',
            name='currency_code',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
